export enum ActionTypes {
  HYDRATE_PRODUCTS = "HYDRATE_PRODUCTS",
  UPDATE_BASKET = "UPDATE_BASKET",
  CLEAR_BASKET = "CLEAR_BASKET",
  HANDLE_STOCK = "HANDLE_STOCK",
  UPDATE_SELECTED_CURRENCY = "UPDATE_SELECTED_CURRENCY",
  UPDATE_SELECTED_PRICE_TYPE = "UPDATE_SELECTED_PRICE_TYPE",
  SET_PAYMENT = "SET_PAYMENT",
  SET_PAYMENT_INFOS = "SET_PAYMENT_INFOS"
}
